In [10]:
import os
import pandas as pd

In [11]:
df = pd.read_csv("D:\codingbase\house-price-prediction\data\cleaned_house_data.csv")

In [12]:
df.head()

,date,bedrooms,bathrooms,sqft_living,floors,waterfront,view,condition,sqft_above,sqft_basement,...,city_SeaTac,city_Seattle,city_Shoreline,city_Skykomish,city_Snoqualmie,city_Snoqualmie Pass,city_Tukwila,city_Vashon,city_Woodinville,city_Yarrow Point
0,2014-05-02,3.0,1.50,1340,1.5,0,0,3,1340,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2014-05-02,5.0,2.50,3650,2.0,0,4,5,3370,280,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2014-05-02,3.0,2.00,1930,1.0,0,0,4,1930,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2014-05-02,3.0,2.25,2000,1.0,0,0,4,1000,1000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2014-05-02,4.0,2.50,1940,1.0,0,0,4,1140,800,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
df_cleaned.head()

,date,bedrooms,bathrooms,sqft_living,floors,waterfront,view,condition,sqft_above,sqft_basement,...,city_SeaTac,city_Seattle,city_Shoreline,city_Skykomish,city_Snoqualmie,city_Snoqualmie Pass,city_Tukwila,city_Vashon,city_Woodinville,city_Yarrow Point
0,2014-05-02,3.0,1.50,1340,1.5,0,0,3,1340,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2014-05-02,5.0,2.50,3650,2.0,0,4,5,3370,280,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2014-05-02,3.0,2.00,1930,1.0,0,0,4,1930,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2014-05-02,3.0,2.25,2000,1.0,0,0,4,1000,1000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2014-05-02,4.0,2.50,1940,1.0,0,0,4,1140,800,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, r2_score
import joblib

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, r2_score
import joblib

# 1. Select your final "Engineered" features
features = ['sqft_living', 'footprint', 'land_utility_ratio', 'bedrooms', 'bathrooms','sqft_basement','sqft_above','condition','view','waterfront','floors','zip_numeric']

X = df_cleaned[features] # Use the encoded data from our previous step
y = df_cleaned['log_price'] # This is your log_price

# 2. Split into Training and Validation sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
from xgboost import XGBRegressor

# Try this 'Safe' XGBoost setup
xgb_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb_model.fit(X_train, y_train)
print("XGBoost Test Score:", xgb_model.score(X_test, y_test))

XGBoost Test Score: 0.7511965610934359